const compendium = {
    weapons: [
        {
            "Nom": "Dague de pierre de sang",
            "Catégorie": "Lame courte",
            "Type": "T/P",
            "pré": 0,
            "Dispo": "R",
            "Dégats": "2D6",
            "Fia": 5,
            "mains": 1,
            "Portée": "-",
            "Effet": "Saignement 25%",
            "Taille": "P",
            "AM": 0,
            "Poids": 1,
            "Prix": 0,
            "Race": "Humain",
            "Page": 145,
            "Source": "ToC"
        },
        {
            "Nom": "Dague",
            "Catégorie": "Lame courte",
            "Type": "T/P",
            "pré": 0,
            "Dispo": "C",
            "Dégats": "1D6+2",
            "Fia": 10,
            "mains": 1,
            "Portée": "-",
            "Effet": "-",
            "Taille": "P",
            "AM": 0,
            "Poids": 1,
            "Prix": 50,
            "Race": "Humain",
            "Page": 73,
            "Source": "Base"
        },
        {
            "Nom": "Stylet",
            "Catégorie": "Lame courte",
            "Type": "T/P",
            "pré": 2,
            "Dispo": "C",
            "Dégats": "1D6",
            "Fia": 5,
            "mains": 1,
            "Portée": "-",
            "Effet": "Dissimulation",
            "Taille": "M",
            "AM": 1,
            "Poids": 0.5,
            "Prix": 275,
            "Race": "Humain",
            "Page": 73,
            "Source": "Base"
        },
        {
            "Nom": "Poignard",
            "Catégorie": "Lame courte",
            "Type": "T/P",
            "pré": 0,
            "Dispo": "C",
            "Dégats": "2D6+2",
            "Fia": 10,
            "mains": 1,
            "Portée": "-",
            "Effet": "Saignement (25%)",
            "Taille": "P",
            "AM": 0,
            "Poids": 1,
            "Prix": 350,
            "Race": "Humain",
            "Page": 2,
            "Source": "Rodolf"
        },
        {
            "Nom": "Jambiya",
            "Catégorie": "Lame courte",
            "Type": "T/P",
            "pré": 2,
            "Dispo": "R",
            "Dégats": "2D6",
            "Fia": 10,
            "mains": 1,
            "Portée": "-",
            "Effet": "Saignement (25%), Perforation",
            "Taille": "P",
            "AM": 1,
            "Poids": 0.5,
            "Prix": 440,
            "Race": "Humain",
            "Page": 73,
            "Source": "Base"
        },
        {
            "Nom": "Dague de parade",
            "Catégorie": "Lame courte",
            "Type": "T/P",
            "pré": 0,
            "Dispo": "C",
            "Dégats": "2D6",
            "Fia": 10,
            "mains": 1,
            "Portée": "-",
            "Effet": "+2 en parade en 2e main",
            "Taille": "P",
            "AM": 0,
            "Poids": 1,
            "Prix": 465,
            "Race": "Humain",
            "Page": 14,
            "Source": "S&F"
        },
        {
            "Nom": "Attrape-lame",
            "Catégorie": "Lame courte",
            "Type": "T/P",
            "pré": 0,
            "Dispo": "C",
            "Dégats": "2D6",
            "Fia": 10,
            "mains": 1,
            "Portée": "-",
            "Effet": "Attrape-lame",
            "Taille": "P",
            "AM": 0,
            "Poids": 1,
            "Prix": 500,
            "Race": "Humain",
            "Page": 8,
            "Source": "Rodolf"
        },
        {
            "Nom": "Dague à rouelle halfeline",
            "Catégorie": "Lame courte",
            "Type": "T/P",
            "pré": 2,
            "Dispo": "R",
            "Dégats": "2D6+2",
            "Fia": 10,
            "mains": 1,
            "Portée": "-",
            "Effet": "Perforation",
            "Taille": "P",
            "AM": 1,
            "Poids": 1,
            "Prix": 485,
            "Race": "Non Humain",
            "Page": 83,
            "Source": "Base"
        },
        {
            "Nom": "Couperet nain",
            "Catégorie": "Lame courte",
            "Type": "T/C",
            "pré": 2,
            "Dispo": "R",
            "Dégats": "3D6",
            "Fia": 15,
            "mains": 1,
            "Portée": "-",
            "Effet": "-",
            "Taille": "P",
            "AM": 1,
            "Poids": 1.5,
            "Prix": 500,
            "Race": "Non Humain",
            "Page": 83,
            "Source": "Base"
        },
        {
            "Nom": "Croc de parade de l'école de la Vipère",
            "Catégorie": "Lame courte",
            "Type": "T/P",
            "pré": 1,
            "Dispo": "R",
            "Dégats": "2D6+2",
            "Fia": 10,
            "mains": 1,
            "Portée": "-",
            "Effet": "Parade sans malus",
            "Taille": "P",
            "AM": 1,
            "Poids": 1,
            "Prix": 0,
            "Race": "Sorceleur",
            "Page": 7,
            "Source": "DLC"
        },
        {
            "Nom": "Croc d'argent de l'école de la Vipère",
            "Catégorie": "Lame courte",
            "Type": "T/P",
            "pré": 2,
            "Dispo": "R",
            "Dégats": "1D6+2",
            "Fia": 10,
            "mains": 1,
            "Portée": "-",
            "Effet": "Poison (30%), Argent (3D6)",
            "Taille": "P",
            "AM": 1,
            "Poids": 1,
            "Prix": 0,
            "Race": "Sorceleur",
            "Page": 4,
            "Source": "DLC"
        },
        {
            "Nom": "Croc d'acier de l'école de la Vipère",
            "Catégorie": "Lame courte",
            "Type": "T/P",
            "pré": 2,
            "Dispo": "R",
            "Dégats": "4D6+2",
            "Fia": 15,
            "mains": 1,
            "Portée": "-",
            "Effet": "Perforation, Poison (30%), Météorite",
            "Taille": "P",
            "AM": 1,
            "Poids": 2,
            "Prix": 0,
            "Race": "Sorceleur",
            "Page": 4,
            "Source": "DLC"
        },
        {
            "Nom": "Epée de fer",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 0,
            "Dispo": "C",
            "Dégats": "2D6+2",
            "Fia": 10,
            "mains": 1,
            "Portée": "-",
            "Effet": "G",
            "Taille": 0,
            "AM": 1,
            "Poids": 150,
            "Prix": "Humain",
            "Page": 0,
            "Source": "Fan made"
        },
        {
            "Nom": "Epée de chevalier",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 0,
            "Dispo": "C",
            "Dégats": "2D6+4",
            "Fia": 15,
            "mains": 1,
            "Portée": "-",
            "Effet": "G",
            "Taille": 0,
            "AM": 2,
            "Poids": 270,
            "Prix": "Humain",
            "Page": 73,
            "Source": "Base"
        },
        {
            "Nom": "Gleddyf",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 2,
            "Dispo": "C",
            "Dégats": "3D6+2",
            "Fia": 10,
            "mains": 1,
            "Portée": "-",
            "Effet": "G",
            "Taille": 0,
            "AM": 3,
            "Poids": 285,
            "Prix": "Humain",
            "Page": 73,
            "Source": "Base"
        },
        {
            "Nom": "Fauchon de chasseur",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 0,
            "Dispo": "C",
            "Dégats": "3D6",
            "Fia": 15,
            "mains": 1,
            "Portée": "-",
            "Effet": "G",
            "Taille": 1,
            "AM": 1.5,
            "Poids": 325,
            "Prix": "Humain",
            "Page": 73,
            "Source": "Base"
        },
        {
            "Nom": "Barème",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 0,
            "Dispo": "C",
            "Dégats": "4D6",
            "Fia": 15,
            "mains": 1,
            "Portée": "-",
            "Effet": "G",
            "Taille": 1,
            "AM": 1.5,
            "Poids": 450,
            "Prix": "Humain",
            "Page": 0,
            "Source": "Fan made"
        },
        {
            "Nom": "Krigsverd",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 2,
            "Dispo": "C",
            "Dégats": "4D6+4",
            "Fia": 10,
            "mains": 1,
            "Portée": "-",
            "Effet": "G",
            "Taille": 0,
            "AM": 2,
            "Poids": 570,
            "Prix": "Humain",
            "Page": 73,
            "Source": "Base"
        },
        {
            "Nom": "Esboda",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 1,
            "Dispo": "P",
            "Dégats": "5D6",
            "Fia": 10,
            "mains": 1,
            "Portée": "-",
            "Effet": "-",
            "Taille": 1,
            "AM": 1.5,
            "Poids": 650,
            "Prix": "Humain",
            "Page": 73,
            "Source": "Base"
        },
        {
            "Nom": "Kord",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 0,
            "Dispo": "R",
            "Dégats": "5D6",
            "Fia": 15,
            "mains": 1,
            "Portée": "-",
            "Effet": "Saignement (25%)",
            "Taille": 1,
            "AM": 1,
            "Poids": 725,
            "Prix": "Humain",
            "Page": 73,
            "Source": "Base"
        },
        {
            "Nom": "Epée Ducal de Toussaint",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 0,
            "Dispo": "R",
            "Dégats": "5D6",
            "Fia": 10,
            "mains": 1,
            "Portée": "-",
            "Effet": "Perforation",
            "Taille": 0,
            "AM": 1,
            "Poids": 800,
            "Prix": "Humain",
            "Page": 165,
            "Source": "BoT"
        },
        {
            "Nom": "Messer elfe",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 2,
            "Dispo": "R",
            "Dégats": "3D6+4",
            "Fia": 15,
            "mains": 1,
            "Portée": "-",
            "Effet": "G",
            "Taille": 2,
            "AM": 2,
            "Poids": 595,
            "Prix": "Non Humain",
            "Page": 83,
            "Source": "Base"
        },
        {
            "Nom": "Sabre de cavalerie vrihedd",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 3,
            "Dispo": "R",
            "Dégats": "4D6+4",
            "Fia": 15,
            "mains": 1,
            "Portée": "-",
            "Effet": "Saignement (25%)",
            "Taille": 2,
            "AM": 2,
            "Poids": 595,
            "Prix": "Non Humain",
            "Page": 83,
            "Source": "Base"
        },
        {
            "Nom": "Deitmenae",
            "Catégorie": "Epées",
            "Type": "T",
            "pré": 2,
            "Dispo": "R",
            "Dégats": "4D6",
            "Fia": 15,
            "mains": 1,
            "Portée": "-",
            "Effet": "2D6 de dégats en plus la nuit. Saignement (50%), Perforation",
            "Taille": 1,
            "AM": 1.5,
            "Poids": 900,
            "Prix": "Non Humain",
            "Page": "",
            "Source": "Fan made"
        },
        {
            "Nom": "Epée d'acier de l'école de la Manticore",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 1,
            "Dispo": "R",
            "Dégats": "5D6+2",
            "Fia": 15,
            "mains": 1,
            "Portée": "-",
            "Effet": "Météorite, Perforation, Equilibré",
            "Taille": "-",
            "AM": 2,
            "Poids": 2.5,
            "Prix": 0,
            "Race": "Sorceleur",
            "Page": 4,
            "Source": "DLC"
        },
        {
            "Nom": "Epée en bois",
            "Catégorie": "Epées",
            "Type": "C",
            "pré": 0,
            "Dispo": "P",
            "Dégats": "2D6",
            "Fia": 10,
            "mains": 2,
            "Portée": "-",
            "Effet": "Non létal",
            "Taille": "G",
            "AM": 0,
            "Poids": 1,
            "Prix": 25,
            "Race": "Humain",
            "Page": "-",
            "Source": "Fan made"
        },
        {
            "Nom": "Épée longue de fer",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 0,
            "Dispo": "P",
            "Dégats": "2D6+2",
            "Fia": 15,
            "mains": 2,
            "Portée": "-",
            "Effet": "-",
            "Taille": "G",
            "AM": 0,
            "Poids": 1.5,
            "Prix": 160,
            "Race": "Humain",
            "Page": 73,
            "Source": "Base"
        },
        {
            "Nom": "Épée de chasseur de sorcières",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 0,
            "Dispo": "I",
            "Dégats": "4D6",
            "Fia": 15,
            "mains": 2,
            "Portée": "-",
            "Effet": "Saignement (25%), 1D6 vs non humain",
            "Taille": "-",
            "AM": 1,
            "Poids": 1.5,
            "Prix": 360,
            "Race": "Humain",
            "Page": "-",
            "Source": "Fan made"
        },
        {
            "Nom": "Lame vicovarienne",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 0,
            "Dispo": "R",
            "Dégats": "5D6+4",
            "Fia": 15,
            "mains": 2,
            "Portée": "-",
            "Effet": "Equilibré",
            "Taille": "-",
            "AM": 1,
            "Poids": 1.5,
            "Prix": 995,
            "Race": "Humain",
            "Page": 73,
            "Source": "Base"
        },
        {
            "Nom": "Epée de Viroledan",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 1,
            "Dispo": "R",
            "Dégats": "4D6+4",
            "Fia": 10,
            "mains": 2,
            "Portée": "-",
            "Effet": "Equilibrée, Saignement(30%), Poison(30%)",
            "Taille": "-",
            "AM": 1,
            "Poids": 2,
            "Prix": 995,
            "Race": "Humain",
            "Page": 165,
            "Source": "BoT"
        },
        {
            "Nom": "Flamberge de Toussaint",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": -1,
            "Dispo": "I",
            "Dégats": "6D6",
            "Fia": 15,
            "mains": 2,
            "Portée": "-",
            "Effet": "Allonge, Charge",
            "Taille": "-",
            "AM": 1,
            "Poids": 3.5,
            "Prix": 1025,
            "Race": "Humain",
            "Page": 165,
            "Source": "BoT"
        },
        {
            "Nom": "Torrwr",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 0,
            "Dispo": "R",
            "Dégats": "6D6",
            "Fia": 15,
            "mains": 2,
            "Portée": "-",
            "Effet": "Météorite, Perforation",
            "Taille": "-",
            "AM": 2,
            "Poids": 2,
            "Prix": 1075,
            "Race": "Humain",
            "Page": 73,
            "Source": "Base"
        },
        {
            "Nom": "Épée en météorite",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 1,
            "Dispo": "R",
            "Dégats": "5D6",
            "Fia": 20,
            "mains": 2,
            "Portée": "-",
            "Effet": "Équilibrée, Météorite",
            "Taille": "-",
            "AM": 2,
            "Poids": 3,
            "Prix": 875,
            "Race": "Non Humain",
            "Page": 83,
            "Source": "Base"
        },
        {
            "Nom": "Sihill de Mahakam",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 2,
            "Dispo": "R",
            "Dégats": "5D6+2",
            "Fia": 15,
            "mains": 2,
            "Portée": "-",
            "Effet": "Étourdissement (25%)",
            "Taille": "-",
            "AM": 2,
            "Poids": 2,
            "Prix": 950,
            "Race": "Non Humain",
            "Page": 0,
            "Source": "Fan made"
        },
        {
            "Nom": "Gwyhyr gnome",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 3,
            "Dispo": "R",
            "Dégats": "5D6+3",
            "Fia": 15,
            "mains": 2,
            "Portée": "-",
            "Effet": "Saignement (50%)",
            "Taille": "-",
            "AM": 2,
            "Poids": 2.5,
            "Prix": 1090,
            "Race": "Non Humain",
            "Page": 83,
            "Source": "Base"
        },
        {
            "Nom": "Lame de Tir Tochair",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 3,
            "Dispo": "R",
            "Dégats": "6D6",
            "Fia": 15,
            "mains": 2,
            "Portée": "-",
            "Effet": "Saignement (25%)",
            "Taille": "-",
            "AM": 2,
            "Poids": 3,
            "Prix": 1175,
            "Race": "Non Humain",
            "Page": 83,
            "Source": "Base"
        },
        {
            "Nom": "Epee de Dol Blathanna",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 1,
            "Dispo": "R",
            "Dégats": "6d6+3",
            "Fia": 15,
            "mains": 2,
            "Portée": "-",
            "Effet": "Equilibré, Météorite",
            "Taille": "-",
            "AM": 2,
            "Poids": 1.2,
            "Prix": 1250,
            "Race": "Non Humain",
            "Page": "-",
            "Source": "Fan made"
        },
        {
            "Nom": "Epée d'acier de witcher",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 0,
            "Dispo": "R",
            "Dégats": "4D6+2",
            "Fia": 15,
            "mains": 2,
            "Portée": "-",
            "Effet": "Météorite, Perforation",
            "Taille": "-",
            "AM": 2,
            "Poids": 2,
            "Prix": 0,
            "Race": "Sorceleur",
            "Page": 247,
            "Source": "Base"
        },
        {
            "Nom": "Epée d'argent de witcher",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 0,
            "Dispo": "R",
            "Dégats": "1D6+2",
            "Fia": 10,
            "mains": 2,
            "Portée": "-",
            "Effet": "Argent (3D6)",
            "Taille": "-",
            "AM": 2,
            "Poids": 1,
            "Prix": 0,
            "Race": "Sorceleur",
            "Page": 247,
            "Source": "Base"
        },
        {
            "Nom": "Epée d'acier de l'école du Loup",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 2,
            "Dispo": "R",
            "Dégats": "5D6+2",
            "Fia": 15,
            "mains": 2,
            "Portée": "-",
            "Effet": "Météorite, Perforation Amélioré",
            "Taille": "-",
            "AM": 2,
            "Poids": 2.5,
            "Prix": 0,
            "Race": "Sorceleur",
            "Page": "-",
            "Source": "DLC"
        },
        {
            "Nom": "Epée d'argent de l'école du Loup",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 2,
            "Dispo": "R",
            "Dégats": "2D6+2",
            "Fia": 10,
            "mains": 2,
            "Portée": "-",
            "Effet": "Argent (3D6), Perforation",
            "Taille": "-",
            "AM": 1,
            "Poids": 1.5,
            "Prix": 0,
            "Race": "Sorceleur",
            "Page": 5,
            "Source": "DLC"
        },
        {
            "Nom": "Epée d'acier de l'école du Griffon",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 1,
            "Dispo": "R",
            "Dégats": "5D6+2",
            "Fia": 15,
            "mains": 2,
            "Portée": "-",
            "Effet": "Météorite, Perforation, Focus(1)",
            "Taille": "-",
            "AM": 2,
            "Poids": 2.5,
            "Prix": 0,
            "Race": "Sorceleur",
            "Page": 3,
            "Source": "DLC"
        },
        {
            "Nom": "Epée d'argent de l'école du griffon",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 1,
            "Dispo": "R",
            "Dégats": "2D6+2",
            "Fia": 10,
            "mains": 2,
            "Portée": "-",
            "Effet": "Argent (3D6), Perforation, Focus(1)",
            "Taille": "-",
            "AM": 2,
            "Poids": 1.5,
            "Prix": 0,
            "Race": "Sorceleur",
            "Page": 3,
            "Source": "DLC"
        },
        {
            "Nom": "Epée d'argent de l'école du Chat",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 2,
            "Dispo": "R",
            "Dégats": "1D6+2",
            "Fia": 10,
            "mains": 2,
            "Portée": "-",
            "Effet": "Argent (3D6), Perforation, Saignement (30%)",
            "Taille": "-",
            "AM": 2,
            "Poids": 1.5,
            "Prix": 0,
            "Race": "Sorceleur",
            "Page": 3,
            "Source": "DLC"
        },
        {
            "Nom": "Epée d'acier de l'école du Chat",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 2,
            "Dispo": "R",
            "Dégats": "4D6+2",
            "Fia": 15,
            "mains": 2,
            "Portée": "-",
            "Effet": "Météorite, Perforation, Saignement (30%)",
            "Taille": "-",
            "AM": 2,
            "Poids": 2.5,
            "Prix": 0,
            "Race": "Sorceleur",
            "Page": 3,
            "Source": "DLC"
        },
        {
            "Nom": "Epée d'argent de l'école de l'Ours",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 0,
            "Dispo": "R",
            "Dégats": "3D6+2",
            "Fia": 10,
            "mains": 2,
            "Portée": "-",
            "Effet": "Argent (3D6), Ablation",
            "Taille": "-",
            "AM": 2,
            "Poids": 1.5,
            "Prix": 0,
            "Race": "Sorceleur",
            "Page": 3,
            "Source": "DLC"
        },
        {
            "Nom": "Epée d'acier de l'école de l'Ours",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 0,
            "Dispo": "R",
            "Dégats": "6D6+2",
            "Fia": 15,
            "mains": 2,
            "Portée": "-",
            "Effet": "Météorite, Perforation, Ablation",
            "Taille": "-",
            "AM": 2,
            "Poids": 2.5,
            "Prix": 0,
            "Race": "Sorceleur",
            "Page": 3,
            "Source": "DLC"
        },
        {
            "Nom": "Epée d'argent de l'école de la Manticore",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 2,
            "Dispo": "R",
            "Dégats": "1D6+2",
            "Fia": 10,
            "mains": 2,
            "Portée": "-",
            "Effet": "Argent (3D6), Equilibré",
            "Taille": "-",
            "AM": 2,
            "Poids": 1.5,
            "Prix": 0,
            "Race": "Sorceleur",
            "Page": 4,
            "Source": "Fan made"
        },
        {
            "Nom": "Coup-de-poing",
            "Catégorie": "Armes contondantes",
            "Type": "C",
            "pré": 1,
            "Dispo": "P",
            "Dégats": "1D6",
            "Fia": 15,
            "mains": 1,
            "Portée": "-",
            "Effet": "S'ajoute au poing",
            "Taille": "M",
            "AM": 1,
            "Poids": 0.5,
            "Prix": 50,
            "Race": "Humain",
            "Page": 73,
            "Source": "Base"
        },
        {
            "Nom": "Nagaïka",
            "Catégorie": "Armes contondantes",
            "Type": "C",
            "pré": 0,
            "Dispo": "C",
            "Dégats": "2D6",
            "Fia": 10,
            "mains": 1,
            "Portée": "-",
            "Effet": "-",
            "Taille": "M",
            "AM": 0,
            "Poids": 1,
            "Prix": 100,
            "Race": "Humain",
            "Page": 0,
            "Source": "Fan made"
        },
        {
            "Nom": "Matraque",
            "Catégorie": "Armes contondantes",
            "Type": "C",
            "pré": 0,
            "Dispo": "P",
            "Dégats": "2D6+2",
            "Fia": 10,
            "mains": 1,
            "Portée": "-",
            "Effet": "Non létal",
            "Taille": "M",
            "AM": 0,
            "Poids": 1,
            "Prix": 140,
            "Race": "Humain",
            "Page": "-",
            "Source": "Fan made"
        },
        {
            "Nom": "Fouet",
            "Catégorie": "Armes contondantes",
            "Type": "T",
            "pré": -1,
            "Dispo": "C",
            "Dégats": "1D6+2",
            "Fia": 10,
            "mains": 1,
            "Portée": "-",
            "Effet": "Allonge, Saisie",
            "Taille": "G",
            "AM": 1,
            "Poids": 2,
            "Prix": 150,
            "Race": "Humain",
            "Page": 14,
            "Source": "S&F"
        },
        {
            "Nom": "Masse d'armes",
            "Catégorie": "Armes contondantes",
            "Type": "C",
            "pré": 0,
            "Dispo": "C",
            "Dégats": "5D6",
            "Fia": 15,
            "mains": 1,
            "Portée": "-",
            "Effet": "-",
            "Taille": "G",
            "AM": 0,
            "Poids": 2,
            "Prix": 525,
            "Race": "Humain",
            "Page": 73,
            "Source": "Base"
        },
        {
            "Nom": "Fléau",
            "Catégorie": "Armes contondantes",
            "Type": "C",
            "pré": -1,
            "Dispo": "I",
            "Dégats": "4D6+2",
            "Fia": 10,
            "mains": 1,
            "Portée": "-",
            "Effet": "Perforation, Saisie",
            "Taille": "G",
            "AM": 1,
            "Poids": 2,
            "Prix": 560,
            "Race": "Humain",
            "Page": 14,
            "Source": "S&F"
        },
        {
            "Nom": "Lamia",
            "Catégorie": "Armes contondantes",
            "Type": "T",
            "pré": -1,
            "Dispo": "R",
            "Dégats": "3D6+1",
            "Fia": 5,
            "mains": 1,
            "Portée": "-",
            "Effet": "Allonge, Saisie, Saignement (100%)",
            "Taille": "P",
            "AM": 1,
            "Poids": 0.5,
            "Prix": 600,
            "Race": "Humain",
            "Page": 14,
            "Source": "S&F"
        },
        {
            "Nom": "Fléau d’armes météorique",
            "Catégorie": "Armes contondantes",
            "Type": "C",
            "pré": 2,
            "Dispo": "R",
            "Dégats": "6D6",
            "Fia": 20,
            "mains": 1,
            "Portée": "-",
            "Effet": "Météorite, Saisie",
            "Taille": "-",
            "AM": 2,
            "Poids": 4,
            "Prix": 900,
            "Race": "Non Humain",
            "Page": 83,
            "Source": "Base"
        },
        {
            "Nom": "Maillet de Paysan",
            "Catégorie": "Armes contondantes",
            "Type": "C",
            "pré": 0,
            "Dispo": "P",
            "Dégats": "5D6",
            "Fia": 5,
            "mains": 2,
            "Portée": "-",
            "Effet": "Ablation",
            "Taille": "-",
            "AM": 0,
            "Poids": 3,
            "Prix": 375,
            "Race": "Humain",
            "Page": 165,
            "Source": "BoT"
        },
        {
            "Nom": "Marteau de Cavalier",
            "Catégorie": "Armes contondantes",
            "Type": "C",
            "pré": 0,
            "Dispo": "C",
            "Dégats": "2D6",
            "Fia": 10,
            "mains": 2,
            "Portée": "-",
            "Effet": "Charge",
            "Taille": "-",
            "AM": 0,
            "Poids": 3,
            "Prix": 800,
            "Race": "Humain",
            "Page": 165,
            "Source": "BoT"
        },
        {
            "Nom": "Masse d'armes à deux mains",
            "Catégorie": "Armes contondantes",
            "Type": "C",
            "pré": 0,
            "Dispo": "I",
            "Dégats": "6D6",
            "Fia": 20,
            "mains": 2,
            "Portée": "-",
            "Effet": "Allonge, Perforation, Ablation",
            "Taille": "G",
            "AM": 0,
            "Poids": 4,
            "Prix": 850,
            "Race": "Humain",
            "Page": "-",
            "Source": "Fan made"
        },
        {
            "Nom": "Maillet kaedwenien",
            "Catégorie": "Armes contondantes",
            "Type": "C",
            "pré": 0,
            "Dispo": "R",
            "Dégats": "6D6+2",
            "Fia": 20,
            "mains": 2,
            "Portée": "-",
            "Effet": "Étourdissement (–2), Météorite",
            "Taille": "-",
            "AM": 0,
            "Poids": 3,
            "Prix": 1100,
            "Race": "Humain",
            "Page": 73,
            "Source": "Base"
        },
        {
            "Nom": "Marteau mahakamien",
            "Catégorie": "Armes contondantes",
            "Type": "C",
            "pré": 0,
            "Dispo": "R",
            "Dégats": "5D6",
            "Fia": 15,
            "mains": 2,
            "Portée": "-",
            "Effet": "Perforation",
            "Taille": "G",
            "AM": 1,
            "Poids": 3.5,
            "Prix": 750,
            "Race": "Non Humain",
            "Page": 83,
            "Source": "Base"
        },
        {
            "Nom": "Hachette",
            "Catégorie": "Hache",
            "Type": "T",
            "pré": 0,
            "Dispo": "P",
            "Dégats": "2D6+1",
            "Fia": 10,
            "mains": 1,
            "Portée": "-",
            "Effet": "-",
            "Taille": "P",
            "AM": 0,
            "Poids": 1,
            "Prix": 205,
            "Race": "Humain",
            "Page": 73,
            "Source": "Base"
        },
        {
            "Nom": "Hache de bataille",
            "Catégorie": "Hache",
            "Type": "T",
            "pré": 0,
            "Dispo": "I",
            "Dégats": "5D6",
            "Fia": 15,
            "mains": 1,
            "Portée": "-",
            "Effet": "-",
            "Taille": "G",
            "AM": 0,
            "Poids": 2,
            "Prix": 525,
            "Race": "Humain",
            "Page": 73,
            "Source": "Base"
        },
        {
            "Nom": "Hache naine",
            "Catégorie": "Hache",
            "Type": "T",
            "pré": 3,
            "Dispo": "R",
            "Dégats": "5D6+3",
            "Fia": 15,
            "mains": 1,
            "Portée": "-",
            "Effet": "-",
            "Taille": "G",
            "AM": 1,
            "Poids": 4,
            "Prix": 740,
            "Race": "Non Humain",
            "Page": 83,
            "Source": "Base"
        },
        {
            "Nom": "Grande hache de bataille",
            "Catégorie": "Hache",
            "Type": "T",
            "pré": 0,
            "Dispo": "I",
            "Dégats": "5D6+3",
            "Fia": 15,
            "mains": 2,
            "Portée": "-",
            "Effet": "-",
            "Taille": "-",
            "AM": 1,
            "Poids": 3,
            "Prix": 650,
            "Race": "Humain",
            "Page": "-",
            "Source": "Rodolf"
        },
        {
            "Nom": "Hallebarde rédanienne",
            "Catégorie": "Armes d'hast",
            "Type": "T",
            "pré": 0,
            "Dispo": "I",
            "Dégats": "6D6+3",
            "Fia": 10,
            "mains": 2,
            "Portée": "-",
            "Effet": "Allonge",
            "Taille": "-",
            "AM": 1,
            "Poids": 4,
            "Prix": 865,
            "Race": "Humain",
            "Page": 73,
            "Source": "Base"
        },
        {
            "Nom": "Marteau de guerre nain",
            "Catégorie": "Armes d'hast",
            "Type": "C/P",
            "pré": 0,
            "Dispo": "R",
            "Dégats": "5D6+2",
            "Fia": 15,
            "mains": 2,
            "Portée": "-",
            "Effet": "Allonge, Étourdissement (-2)",
            "Taille": "-",
            "AM": 1,
            "Poids": 4,
            "Prix": 835,
            "Race": "Non Humain",
            "Page": 83,
            "Source": "Base"
        },
        {
            "Nom": "Vouge elfe",
            "Catégorie": "Armes d'hast",
            "Type": "T/P/C",
            "pré": 2,
            "Dispo": "r",
            "Dégats": "4D6+3",
            "Fia": 10,
            "mains": 2,
            "Portée": "-",
            "Effet": "Allonge, Saignement (25%)",
            "Taille": "-",
            "AM": 2,
            "Poids": 3,
            "Prix": 925,
            "Race": "Non Humain",
            "Page": 83,
            "Source": "Base"
        },
        {
            "Nom": "Couteau de lancer",
            "Catégorie": "Armes de jet",
            "Type": "P",
            "Pré": 0,
            "Dispo": "P",
            "Dégâts": "1D6",
            "Fia": 5,
            "Mains": 1,
            "Portée": "Corps x4m",
            "Effet": "-",
            "Taille": "M",
            "AM": 0,
            "Poids": 0.5,
            "Prix": 50,
            "Race": "Humain",
            "Page": 74,
            "Source": "Base"
          },
          {
            "Nom": "Hache de lancer",
            "Catégorie": "Armes de jet",
            "Type": "P",
            "Pré": 0,
            "Dispo": "P",
            "Dégâts": "2D6",
            "Fia": 10,
            "Mains": 1,
            "Portée": "Corps x2m",
            "Effet": "-",
            "Taille": "P",
            "AM": 0,
            "Poids": 1.5,
            "Prix": 75,
            "Race": "Humain",
            "Page": 75,
            "Source": "Base"
          },
          {
            "Nom": "Orion",
            "Catégorie": "Armes de jet",
            "Type": "T",
            "Pré": 1,
            "Dispo": "I",
            "Dégâts": "1D6",
            "Fia": 5,
            "Mains": 1,
            "Portée": "Corps x4m",
            "Effet": "-",
            "Taille": "M",
            "AM": 0,
            "Poids": 0.1,
            "Prix": 100,
            "Race": "Humain",
            "Page": 74,
            "Source": "Base"
          },
          {
            "Nom": "Griffe de harpie empoisonnée",
            "Catégorie": "Armes de jet",
            "Type": "T/P",
            "Pré": 1,
            "Dispo": "P",
            "Dégâts": "1D6",
            "Fia": 10,
            "Mains": 1,
            "Portée": "Corps",
            "Effet": "Poison 90%, Équilibré",
            "Taille": "P",
            "AM": 0,
            "Poids": 0.5,
            "Prix": 450,
            "Race": "Humain",
            "Page": 8,
            "Source": "Rodolf"
          },
          {
            "Nom": "Arc court",
            "Catégorie": "Arc",
            "Type": "P",
            "Pré": 0,
            "Dispo": "P",
            "Dégâts": "3D6+3",
            "Fia": 10,
            "Mains": 2,
            "Portée": "100m",
            "Effet": "-",
            "Taille": "G",
            "AM": 0,
            "Poids": 1,
            "Prix": 290,
            "Race": "Humain",
            "Page": 74,
            "Source": "Base"
          },
          {
            "Nom": "Arc long",
            "Catégorie": "Arc",
            "Type": "P",
            "Pré": 0,
            "Dispo": "P",
            "Dégâts": "4D6",
            "Fia": 10,
            "Mains": 2,
            "Portée": "200m",
            "Effet": "-",
            "Taille": "-",
            "AM": 1,
            "Poids": 3,
            "Prix": 475,
            "Race": "Humain",
            "Page": 74,
            "Source": "Base"
          },
          {
            "Nom": "Arc de guerre",
            "Catégorie": "Arc",
            "Type": "P",
            "Pré": 0,
            "Dispo": "P",
            "Dégâts": "6D6",
            "Fia": 15,
            "Mains": 2,
            "Portée": "300m",
            "Effet": "-",
            "Taille": "-",
            "AM": 1,
            "Poids": 3,
            "Prix": 835,
            "Race": "Humain",
            "Page": 74,
            "Source": "Base"
          },
          {
            "Nom": "Arc de voyage elfe",
            "Catégorie": "Arc",
            "Type": "P",
            "Pré": 1,
            "Dispo": "R",
            "Dégâts": "4D6",
            "Fia": 10,
            "Mains": 2,
            "Portée": "200m",
            "Effet": "-",
            "Taille": "G",
            "AM": 1,
            "Poids": 1,
            "Prix": 575,
            "Race": "Non Humain",
            "Page": 83,
            "Source": "Base"
          },
          {
            "Nom": "Arc de commando elfe",
            "Catégorie": "Arc",
            "Type": "P",
            "Pré": 1,
            "Dispo": "R",
            "Dégâts": "5D6",
            "Fia": 10,
            "Mains": 2,
            "Portée": "250m",
            "Effet": "Perforation",
            "Taille": "-",
            "AM": 1,
            "Poids": 2,
            "Prix": 800,
            "Race": "Non Humain",
            "Page": 0,
            "Source": "Fan made"
          },
          {
            "Nom": "Zefhar elfe",
            "Catégorie": "Arc",
            "Type": "P",
            "Pré": 2,
            "Dispo": "R",
            "Dégâts": "6D6",
            "Fia": 10,
            "Mains": 2,
            "Portée": "350m",
            "Effet": "Perforation améliorée",
            "Taille": "-",
            "AM": 2,
            "Poids": 2.5,
            "Prix": 1100,
            "Race": "Non Humain",
            "Page": 83,
            "Source": "Base"
          },
          {
            "Nom": "Arbalète de poing",
            "Catégorie": "Arbalètes",
            "Type": "P",
            "pré": 1,
            "Dispo": "P",
            "Dégats": "2D6+2",
            "Fia": 10,
            "mains": 1,
            "Portée": "100m",
            "Effet": "Rechargement lent, Perforation*",
            "Taille": "G",
            "AM": 1,
            "Poids": 1,
            "Prix": 290,
            "Race": "Humain",
            "Page": 74,
            "Source": "Base",
            "Description": "",
            "Craft": ""
          },
          {
            "Nom": "Arbalète de poing gnome",
            "Catégorie": "Arbalètes",
            "Type": "P",
            "pré": 3,
            "Dispo": "R",
            "Dégats": "2D6",
            "Fia": 10,
            "mains": 1,
            "Portée": "100m",
            "Effet": "Rechargement lent, Perforation*",
            "Taille": "P",
            "AM": 1,
            "Poids": 1,
            "Prix": 425,
            "Race": "Non Humain",
            "Page": 83,
            "Source": "Base",
            "Description": "",
            "Craft": ""
          },
          {
            "Nom": "Arbalète de l'École de l'Ours",
            "Catégorie": "Arbalètes",
            "Type": "L",
            "pré": 1,
            "Dispo": "R",
            "Dégats": "4d6+2",
            "Fia": 5,
            "mains": 1,
            "Portée": "50m",
            "Effet": "Rechargement lent, Perforation*",
            "Taille": "G",
            "AM": 1,
            "Poids": 1,
            "Prix": 0,
            "Race": "Sorceleur",
            "Page": 3,
            "Source": "DLC",
            "Description": "",
            "Craft": ""
          },
          {
            "Nom": "Arbalète de l'École du Chat",
            "Catégorie": "Arbalètes",
            "Type": "L",
            "pré": 1,
            "Dispo": "R",
            "Dégats": "2d6+2",
            "Fia": 5,
            "mains": 1,
            "Portée": "50m",
            "Effet": "Rechargement lent, Perforation*, Equilibré",
            "Taille": "G",
            "AM": 1,
            "Poids": 0,
            "Prix": 0,
            "Race": "Sorceleur",
            "Page": 3,
            "Source": "DLC",
            "Description": "",
            "Craft": ""
          },
          {
            "Nom": "Arbalète de l'École du Griffon",
            "Catégorie": "Arbalètes",
            "Type": "L",
            "pré": 1,
            "Dispo": "R",
            "Dégats": "2d6+2",
            "Fia": 5,
            "mains": 1,
            "Portée": "50m",
            "Effet": "Rechargement lent, Perforation Amélioré*",
            "Taille": "G",
            "AM": 1,
            "Poids": 0,
            "Prix": 0,
            "Race": "Sorceleur",
            "Page": 3,
            "Source": "DLC",
            "Description": "",
            "Craft": ""
          },
          {
            "Nom": "Arbalète de l'École de la Vipère",
            "Catégorie": "Arbalètes",
            "Type": "L",
            "pré": 1,
            "Dispo": "R",
            "Dégats": "2d6+2",
            "Fia": 5,
            "mains": 1,
            "Portée": "50m",
            "Effet": "Rechargement lent, Perforation*, Poison 75%",
            "Taille": "G",
            "AM": 1,
            "Poids": 0,
            "Prix": 0,
            "Race": "Sorceleur",
            "Page": 3,
            "Source": "Fan made",
            "Description": "",
            "Craft": ""
          },
          {
            "Nom": "Arbalète de l'École du Loup",
            "Catégorie": "Arbalètes",
            "Type": "L",
            "pré": 1,
            "Dispo": "R",
            "Dégats": "2d6+2",
            "Fia": 5,
            "mains": 1,
            "Portée": "50m",
            "Effet": "Rechargement lent, Perforation*, Ablation",
            "Taille": "G",
            "AM": 1,
            "Poids": 0,
            "Prix": 0,
            "Race": "Sorceleur",
            "Page": 3,
            "Source": "Fan made",
            "Description": "",
            "Craft": ""
          },
          {
            "Nom": "Arbalète de l'École de la Manticore",
            "Catégorie": "Arbalètes",
            "Type": "L",
            "pré": 1,
            "Dispo": "R",
            "Dégats": "2d6+2",
            "Fia": 5,
            "mains": 1,
            "Portée": "50m",
            "Effet": "Rechargement lent, Perforation*, Saignement 75%",
            "Taille": "G",
            "AM": 1,
            "Poids": 1,
            "Prix": 0,
            "Race": "Sorceleur",
            "Page": 3,
            "Source": "Fan made",
            "Description": "",
            "Craft": ""
          },
          {
            "Nom": "Arbalète",
            "Catégorie": "Arbalètes",
            "Type": "P",
            "pré": 2,
            "Dispo": "P",
            "Dégats": "4D6+2",
            "Fia": 5,
            "mains": 2,
            "Portée": "200m",
            "Effet": "Rechargement lent, Perforation*",
            "Taille": "-",
            "AM": 1,
            "Poids": 3,
            "Prix": 455,
            "Race": "Humain",
            "Page": 74,
            "Source": "Base",
            "Description": "",
            "Craft": ""
          },
          {
            "Nom": "Arbalète de chasseur",
            "Catégorie": "Arbalètes",
            "Type": "P",
            "pré": 3,
            "Dispo": "R",
            "Dégats": "6D6",
            "Fia": 15,
            "mains": 2,
            "Portée": "300m",
            "Effet": "Rechargement lent, Perforation améliorée*",
            "Taille": "-",
            "AM": 2,
            "Poids": 4,
            "Prix": 1125,
            "Race": "Humain",
            "Page": 74,
            "Source": "Base",
            "Description": "",
            "Craft": ""
          },
          {
            "Nom": "Scorpion",
            "Catégorie": "Arbalètes",
            "Type": "P",
            "pré": 0,
            "Dispo": "R",
            "Dégats": "10D6",
            "Fia": 20,
            "mains": 2,
            "Portée": "200m",
            "Effet": "Rechargement en equipe, Monté",
            "Taille": "-",
            "AM": 0,
            "Poids": 40,
            "Prix": 2500,
            "Race": "Humain",
            "Page": 8,
            "Source": "Rodolf",
            "Description": "",
            "Craft": ""
          },
          {
            "Nom": "Arbalète lourde naine",
            "Catégorie": "Arbalètes",
            "Type": "P",
            "pré": 2,
            "Dispo": "I",
            "Dégats": "5D6",
            "Fia": 15,
            "mains": 2,
            "Portée": "300m",
            "Effet": "Rechargement lent, Perforation*",
            "Taille": "-",
            "AM": 2,
            "Poids": 3,
            "Prix": 600,
            "Race": "Non Humain",
            "Page": 0,
            "Source": "Rodolf",
            "Description": "",
            "Craft": ""
          },
          {
            "Nom": "Contondant",
            "Catégorie": "Projectiles",
            "Type": "C",
            "pré": "-",
            "Dispo": "C",
            "Dégats": "-",
            "Fia": 10,
            "mains": 0,
            "Portée": "-",
            "Effet": "Non létal",
            "Taille": "G",
            "AM": 0,
            "Poids": 0.1,
            "Prix": 5,
            "Race": "Humain",
            "Page": 74,
            "Source": "Base",
            "Description": "",
            "Craft": ""
          },
          {
            "Nom": "Standard",
            "Catégorie": "Projectiles",
            "Type": "P",
            "pré": "-",
            "Dispo": "P",
            "Dégats": "-",
            "Fia": 10,
            "mains": 0,
            "Portée": "-",
            "Effet": "-",
            "Taille": "G",
            "AM": 0,
            "Poids": 0.5,
            "Prix": 10,
            "Race": "Humain",
            "Page": 74,
            "Source": "Base",
            "Description": "",
            "Craft": ""
          },
          {
            "Nom": "Tête large",
            "Catégorie": "Projectiles",
            "Type": "P",
            "pré": "-",
            "Dispo": "C",
            "Dégats": "-",
            "Fia": 10,
            "mains": 0,
            "Portée": "-",
            "Effet": "Saignement (100%)",
            "Taille": "G",
            "AM": 0,
            "Poids": 0.1,
            "Prix": 10,
            "Race": "Humain",
            "Page": 74,
            "Source": "Base",
            "Description": "",
            "Craft": ""
          },
          {
            "Nom": "Argent",
            "Catégorie": "Projectiles",
            "Type": "P",
            "pré": "-",
            "Dispo": "I",
            "Dégats": "-",
            "Fia": 10,
            "mains": 0,
            "Portée": "-",
            "Effet": "Argent (2D6)",
            "Taille": "G",
            "AM": 0,
            "Poids": 0.1,
            "Prix": 10,
            "Race": "Humain",
            "Page": "",
            "Source": "Fan made",
            "Description": "",
            "Craft": ""
          },
          {
            "Nom": "De précision",
            "Catégorie": "Projectiles",
            "Type": "P",
            "pré": "-",
            "Dispo": "C",
            "Dégats": "-",
            "Fia": 10,
            "mains": 0,
            "Portée": "-",
            "Effet": "Perforant",
            "Taille": "G",
            "AM": 0,
            "Poids": 0.1,
            "Prix": 15,
            "Race": "Humain",
            "Page": 74,
            "Source": "Base",
            "Description": "",
            "Craft": ""
          },
          {
            "Nom": "Pisteur",
            "Catégorie": "Projectiles",
            "Type": "P",
            "pré": "-",
            "Dispo": "R",
            "Dégats": "0",
            "Fia": 10,
            "mains": 0,
            "Portée": "-",
            "Effet": "Permet de pister sans jet de pistage pendant 12h.",
            "Taille": "G",
            "AM": 0,
            "Poids": 0.5,
            "Prix": 22,
            "Race": "Humain",
            "Page": 255,
            "Source": "Base",
            "Description": "",
            "Craft": ""
          },
          {
            "Nom": "Projectile Scorpion",
            "Catégorie": "Projectiles",
            "Type": "C",
            "pré": "-",
            "Dispo": "R",
            "Dégats": "-",
            "Fia": 10,
            "mains": 0,
            "Portée": "-",
            "Effet": "-",
            "Taille": "G",
            "AM": 0,
            "Poids": 2,
            "Prix": 50,
            "Race": "Humain",
            "Page": 8,
            "Source": "Rodolf",
            "Description": "",
            "Craft": ""
          },
          {
            "Nom": "Fragmentation",
            "Catégorie": "Projectiles",
            "Type": "P",
            "pré": "-",
            "Dispo": "R",
            "Dégats": "0",
            "Fia": 10,
            "mains": 0,
            "Portée": "-",
            "Effet": "Une flèche par point au dessus SD défense, dégât max et 3 fleches max",
            "Taille": "G",
            "AM": 0,
            "Poids": 0.5,
            "Prix": 54,
            "Race": "Humain",
            "Page": 255,
            "Source": "Base",
            "Description": "",
            "Craft": ""
          },
          {
            "Nom": "Projectile Scorpion Briseur",
            "Catégorie": "Projectiles",
            "Type": "C",
            "pré": "-",
            "Dispo": "R",
            "Dégats": "-",
            "Fia": 10,
            "mains": 0,
            "Portée": "-",
            "Effet": "Ablation",
            "Taille": "G",
            "AM": 0,
            "Poids": 2,
            "Prix": 75,
            "Race": "Humain",
            "Page": 8,
            "Source": "Rodolf",
            "Description": "",
            "Craft": ""
          },
          {
            "Nom": "Projectile Scorpion Perçant",
            "Catégorie": "Projectiles",
            "Type": "C",
            "pré": "-",
            "Dispo": "R",
            "Dégats": "-",
            "Fia": 10,
            "mains": 0,
            "Portée": "-",
            "Effet": "Perforation",
            "Taille": "G",
            "AM": 0,
            "Poids": 2,
            "Prix": 75,
            "Race": "Humain",
            "Page": 8,
            "Source": "Rodolf",
            "Description": "",
            "Craft": ""
          },
          {
            "Nom": "Explosif",
            "Catégorie": "Projectiles",
            "Type": "E",
            "pré": "-",
            "Dispo": "R",
            "Dégats": "4D6",
            "Fia": 10,
            "mains": 0,
            "Portée": "-",
            "Effet": "Explosion de feu sur 2m toute les zones du corps.",
            "Taille": "G",
            "AM": 0,
            "Poids": 0.5,
            "Prix": 108,
            "Race": "Humain",
            "Page": 255,
            "Source": "Base",
            "Description": "",
            "Craft": ""
          },
          {
            "Nom": "Fouisseuse elfe",
            "Catégorie": "Projectiles",
            "Type": "P",
            "pré": "-",
            "Dispo": "R",
            "Dégats": "-",
            "Fia": 10,
            "mains": 0,
            "Portée": "-",
            "Effet": "Saignement (10 %)",
            "Taille": "G",
            "AM": 0,
            "Poids": 0.1,
            "Prix": 50,
            "Race": "Non Humain",
            "Page": 84,
            "Source": "Base",
            "Description": "",
            "Craft": ""
          },
          {
            "Nom": "Impact nain",
            "Catégorie": "Projectiles",
            "Type": "P",
            "pré": "-",
            "Dispo": "R",
            "Dégats": "-",
            "Fia": 15,
            "mains": 0,
            "Portée": "-",
            "Effet": "Ablation",
            "Taille": "-",
            "AM": 0,
            "Poids": 0.1,
            "Prix": 50,
            "Race": "Non Humain",
            "Page": 84,
            "Source": "Base",
            "Description": "",
            "Craft": ""
          },
          {
            "Nom": "Bâton de mage",
            "Catégorie": "Bâtons",
            "Type": "C",
            "pré": "0",
            "Dispo": "C",
            "Dégats": "1D6+2",
            "Fia": 15,
            "mains": 2,
            "Portée": "-",
            "Effet": "Allonge, Focus (1)",
            "Taille": "-",
            "AM": 1,
            "Poids": 2.5,
            "Prix": 335,
            "Race": "Humain",
            "Page": 74,
            "Source": "Base",
            "Description": "",
            "Craft": ""
          },
          {
            "Nom": "Houlette",
            "Catégorie": "Bâtons",
            "Type": "T/P",
            "pré": "0",
            "Dispo": "I",
            "Dégats": "2D6",
            "Fia": 10,
            "mains": 2,
            "Portée": "-",
            "Effet": "Allonge, Focus(1), Saisie",
            "Taille": "-",
            "AM": 1,
            "Poids": 3.5,
            "Prix": 550,
            "Race": "Humain",
            "Page": 74,
            "Source": "Base",
            "Description": "",
            "Craft": ""
          },
          {
            "Nom": "Baton de fer",
            "Catégorie": "Bâtons",
            "Type": "C",
            "pré": "0",
            "Dispo": "I",
            "Dégats": "3D6",
            "Fia": 15,
            "mains": 2,
            "Portée": "-",
            "Effet": "Allonge, Focus (2)",
            "Taille": "-",
            "AM": 1,
            "Poids": 4,
            "Prix": 675,
            "Race": "Humain",
            "Page": 74,
            "Source": "Base",
            "Description": "",
            "Craft": ""
          },
          {
            "Nom": "Bâton-cristal",
            "Catégorie": "Bâtons",
            "Type": "C",
            "pré": "0",
            "Dispo": "R",
            "Dégats": "2D6+2",
            "Fia": 10,
            "mains": 2,
            "Portée": "-",
            "Effet": "Allonge, Focus(3); Focus supérieur",
            "Taille": "-",
            "AM": 1,
            "Poids": 2.5,
            "Prix": 835,
            "Race": "Humain",
            "Page": 74,
            "Source": "Base",
            "Description": "",
            "Craft": ""
          },
          {
            "Nom": "Bâton gnome",
            "Catégorie": "Bâtons",
            "Type": "C",
            "pré": "1",
            "Dispo": "R",
            "Dégats": "3D6+2",
            "Fia": 15,
            "mains": 2,
            "Portée": "-",
            "Effet": "Allonge, Focus (3)",
            "Taille": "g",
            "AM": 2,
            "Poids": 2.5,
            "Prix": 910,
            "Race": "Non Humain",
            "Page": 83,
            "Source": "Base",
            "Description": "",
            "Craft": ""
          },
          {
            "Nom": "Bâton de marche elfe",
            "Catégorie": "Bâtons",
            "Type": "C",
            "pré": "1",
            "Dispo": "R",
            "Dégats": "3D6",
            "Fia": 10,
            "mains": 2,
            "Portée": "-",
            "Effet": "Allonge, Focus (3), Focus supérieur",
            "Taille": "-",
            "AM": 2,
            "Poids": 1.5,
            "Prix": 975,
            "Race": "Non Humain",
            "Page": 83,
            "Source": "Base",
            "Description": "",
            "Craft": ""
          },
          {
            "Nom": "Soleil de Zerrikania",
            "Catégorie": "Bombes",
            "Type": "E",
            "pré": "0",
            "Dispo": "R",
            "Dégats": "0",
            "Fia": 0,
            "mains": 1,
            "Portée": "4m",
            "Effet": "Aveugle la cible.",
            "Taille": "P",
            "AM": 0,
            "Poids": 1,
            "Prix": 120,
            "Race": "Humain",
            "Page": 8,
            "Source": "DLC",
            "Description": "",
            "Craft": ""
          },
          {
            "Nom": "Vesse de loup du diable",
            "Catégorie": "Bombes",
            "Type": "E",
            "pré": "0",
            "Dispo": "R",
            "Dégats": "2D6",
            "Fia": 0,
            "mains": 1,
            "Portée": "CORx4m",
            "Effet": "Poison (100 %), double les dégâts du poison sur 4m.",
            "Taille": "P",
            "AM": 0,
            "Poids": 1,
            "Prix": 138,
            "Race": "Humain",
            "Page": 255,
            "Source": "Base",
            "Description": "",
            "Craft": ""
          },
          {
            "Nom": "Samum",
            "Catégorie": "Bombes",
            "Type": "E",
            "pré": "0",
            "Dispo": "R",
            "Dégats": "0",
            "Fia": 0,
            "mains": 1,
            "Portée": "CORx4m",
            "Effet": "Jet de sauvegarde Etou à -2 et aveugler 6 rounds sur 8m.",
            "Taille": "P",
            "AM": 0,
            "Poids": 1,
            "Prix": 147,
            "Race": "Humain",
            "Page": 255,
            "Source": "Base",
            "Description": "",
            "Craft": ""
          },
          {
            "Nom": "Ruche",
            "Catégorie": "Bombes",
            "Type": "E",
            "pré": "0",
            "Dispo": "R",
            "Dégats": "7D6",
            "Fia": 0,
            "mains": 1,
            "Portée": "CORx4m",
            "Effet": "Feu (25 %) sur 4m",
            "Taille": "P",
            "AM": 0,
            "Poids": 1,
            "Prix": 159,
            "Race": "Humain",
            "Page": 255,
            "Source": "Base",
            "Description": "",
            "Craft": ""
          },
          {
            "Nom": "Étoile dansante",
            "Catégorie": "Bombes",
            "Type": "E",
            "pré": "0",
            "Dispo": "R",
            "Dégats": "5d6",
            "Fia": 0,
            "mains": 1,
            "Portée": "CORx4m",
            "Effet": "Feu (100 %)",
            "Taille": "P",
            "AM": 0,
            "Poids": 1,
            "Prix": 162,
            "Race": "Humain",
            "Page": 255,
            "Source": "Base",
            "Description": "",
            "Craft": ""
          },
          {
            "Nom": "Brume rouge",
            "Catégorie": "Bombes",
            "Type": "E",
            "pré": "0",
            "Dispo": "R",
            "Dégats": "2D6",
            "Fia": 0,
            "mains": 1,
            "Portée": "CORx4m",
            "Effet": "Nuage rouge (4m), jet de Résilience (SD 15) pour éviter d'attaquer la cible la plus proche pendant 3 rounds.",
            "Taille": "P",
            "AM": 0,
            "Poids": 1,
            "Prix": 169,
            "Race": "Humain",
            "Page": 255,
            "Source": "Fan made",
            "Description": "",
            "Craft": ""
          },
          {
            "Nom": "Rêve de dragon",
            "Catégorie": "Bombes",
            "Type": "E",
            "pré": "0",
            "Dispo": "R",
            "Dégats": "0",
            "Fia": 0,
            "mains": 1,
            "Portée": "CORx4m",
            "Effet": "Nuage de gaz inflammable pendant 3 rounds sur 8m. Si enflammé, 5D6 dégâts + 75% feu",
            "Taille": "P",
            "AM": 0,
            "Poids": 1,
            "Prix": 177,
            "Race": "Humain",
            "Page": 255,
            "Source": "Base",
            "Description": "",
            "Craft": ""
          },
          {
            "Nom": "Vent du nord",
            "Catégorie": "Bombes",
            "Type": "E",
            "pré": "0",
            "Dispo": "R",
            "Dégats": "2D6",
            "Fia": 0,
            "mains": 1,
            "Portée": "CORx4m",
            "Effet": "Geler pour 8 rounds, SD18 de Physique pour sortir du gel ou jusqu'à un coup.",
            "Taille": "P",
            "AM": 0,
            "Poids": 1,
            "Prix": 177,
            "Race": "Humain",
            "Page": 255,
            "Source": "Base",
            "Description": "",
            "Craft": ""
          },
          {
            "Nom": "Poussière de lune",
            "Catégorie": "Bombes",
            "Type": "E",
            "pré": "0",
            "Dispo": "R",
            "Dégats": "0",
            "Fia": 0,
            "mains": 1,
            "Portée": "CORx4m",
            "Effet": "Rend tangible et visible pendant 20 rounds. Empêche transformation et régénération sur 8m.",
            "Taille": "P",
            "AM": 0,
            "Poids": 1,
            "Prix": 199,
            "Race": "Humain",
            "Page": 255,
            "Source": "Base",
            "Description": "",
            "Craft": ""
          },
          {
            "Nom": "Bombe au dimeritium",
            "Catégorie": "Bombes",
            "Type": "E",
            "pré": "0",
            "Dispo": "R",
            "Dégats": "0",
            "Fia": 0,
            "mains": 1,
            "Portée": "CORx4m",
            "Effet": "Interdit l’usage de magie dans la zone pendant 20 rounds sur 8m",
            "Taille": "P",
            "AM": 0,
            "Poids": 1,
            "Prix": 264,
            "Race": "Humain",
            "Page": 255,
            "Source": "Base",
            "Description": "",
            "Craft": ""
          },
          {
            "Nom": "Armes",
            "Catégorie": "Pièges",
            "Type": "P",
            "pré": 0,
            "Dispo": "R",
            "Dégats": "2D6",
            "Fia": 0,
            "mains": 1,
            "Portée": "4m",
            "Effet": "Explosion d'une peinture avec une odeur pendant 24h qui se sent à 1,5km. +5 au jet pour remarquer ou pister.",
            "Taille": "M",
            "AM": 0,
            "Poids": 2,
            "Prix": 57,
            "Race": "Humain",
            "Page": 254,
            "Source": "Base",
            "Description": "",
            "Craft": ""
          },
          {
            "Nom": "Armes",
            "Catégorie": "Pièges",
            "Type": "P",
            "pré": 0,
            "Dispo": "C",
            "Dégats": "3D6",
            "Fia": 0,
            "mains": 1,
            "Portée": "-",
            "Effet": "Saignement (50%)",
            "Taille": "M",
            "AM": 0,
            "Poids": 2,
            "Prix": 60,
            "Race": "Humain",
            "Page": 254,
            "Source": "Fan made",
            "Description": "",
            "Craft": ""
          },
          {
            "Nom": "Armes",
            "Catégorie": "Pièges",
            "Type": "P",
            "pré": 0,
            "Dispo": "R",
            "Dégats": "5D6",
            "Fia": 0,
            "mains": 1,
            "Portée": "4m",
            "Effet": "Saignement (80%)",
            "Taille": "M",
            "AM": 0,
            "Poids": 2,
            "Prix": 111,
            "Race": "Humain",
            "Page": 254,
            "Source": "Base",
            "Description": "",
            "Craft": ""
          },
          {
            "Nom": "Armes",
            "Catégorie": "Pièges",
            "Type": "P",
            "pré": 0,
            "Dispo": "R",
            "Dégats": "5D6",
            "Fia": 0,
            "mains": 1,
            "Portée": "4m",
            "Effet": "Feu (75%)",
            "Taille": "M",
            "AM": 0,
            "Poids": 2,
            "Prix": 121,
            "Race": "Humain",
            "Page": 254,
            "Source": "Base",
            "Description": "",
            "Craft": ""
          },
          {
            "Nom": "Armes",
            "Catégorie": "Pièges",
            "Type": "P",
            "pré": 0,
            "Dispo": "R",
            "Dégats": "2D6",
            "Fia": 0,
            "mains": 1,
            "Portée": "4m",
            "Effet": "Geler pour 8 rounds, SD18 de Physique pour sortir du gel ou jusqu'à un coup.",
            "Taille": "M",
            "AM": 0,
            "Poids": 2,
            "Prix": 126,
            "Race": "Humain",
            "Page": 254,
            "Source": "Base",
            "Description": "",
            "Craft": ""
          },
          {
            "Nom": "Armes",
            "Catégorie": "Pièges",
            "Type": "P",
            "pré": 0,
            "Dispo": "R",
            "Dégats": "7D6",
            "Fia": 0,
            "mains": 1,
            "Portée": "4m",
            "Effet": "-",
            "Taille": "M",
            "AM": 0,
            "Poids": 2,
            "Prix": 144,
            "Race": "Humain",
            "Page": 254,
            "Source": "Base",
            "Description": "",
            "Craft": ""
          },
          {
            "Nom": "Armes",
            "Catégorie": "Pièges",
            "Type": "P",
            "pré": 0,
            "Dispo": "R",
            "Dégats": 0,
            "Fia": 0,
            "mains": 1,
            "Portée": "4m",
            "Effet": "Jet de résilience SD18 ou combattre la personne la plus proche jusqu'à réussir son jet.",
            "Taille": "M",
            "AM": 0,
            "Poids": 2,
            "Prix": 144,
            "Race": "Humain",
            "Page": 254,
            "Source": "Base",
            "Description": "",
            "Craft": ""
          }
    ]
}