const shop = {
    weapons: [
        {
            "Nom": "Dague de pierre de sang",
            "Catégorie": "Lame courte",
            "Type": "T/P",
            "pré": 0,
            "Dispo": "R",
            "Dégats": "2D6",
            "Fia": 5,
            "mains": 1,
            "Portée": "-",
            "Effet": "Saignement 25%",
            "Taille": "P",
            "AM": 0,
            "Poids": 1,
            "Prix": 0,
            "Race": "Humain",
            "Page": 145,
            "Source": "ToC"
        },
        {
            "Nom": "Dague",
            "Catégorie": "Lame courte",
            "Type": "T/P",
            "pré": 0,
            "Dispo": "C",
            "Dégats": "1D6+2",
            "Fia": 10,
            "mains": 1,
            "Portée": "-",
            "Effet": "-",
            "Taille": "P",
            "AM": 0,
            "Poids": 1,
            "Prix": 50,
            "Race": "Humain",
            "Page": 73,
            "Source": "Base"
        },
        {
            "Nom": "Stylet",
            "Catégorie": "Lame courte",
            "Type": "T/P",
            "pré": 2,
            "Dispo": "C",
            "Dégats": "1D6",
            "Fia": 5,
            "mains": 1,
            "Portée": "-",
            "Effet": "Dissimulation",
            "Taille": "M",
            "AM": 1,
            "Poids": 0.5,
            "Prix": 275,
            "Race": "Humain",
            "Page": 73,
            "Source": "Base"
        },
        {
            "Nom": "Poignard",
            "Catégorie": "Lame courte",
            "Type": "T/P",
            "pré": 0,
            "Dispo": "C",
            "Dégats": "2D6+2",
            "Fia": 10,
            "mains": 1,
            "Portée": "-",
            "Effet": "Saignement (25%)",
            "Taille": "P",
            "AM": 0,
            "Poids": 1,
            "Prix": 350,
            "Race": "Humain",
            "Page": 2,
            "Source": "Rodolf"
        },
        {
            "Nom": "Jambiya",
            "Catégorie": "Lame courte",
            "Type": "T/P",
            "pré": 2,
            "Dispo": "R",
            "Dégats": "2D6",
            "Fia": 10,
            "mains": 1,
            "Portée": "-",
            "Effet": "Saignement (25%), Perforation",
            "Taille": "P",
            "AM": 1,
            "Poids": 0.5,
            "Prix": 440,
            "Race": "Humain",
            "Page": 73,
            "Source": "Base"
        },
        {
            "Nom": "Dague de parade",
            "Catégorie": "Lame courte",
            "Type": "T/P",
            "pré": 0,
            "Dispo": "C",
            "Dégats": "2D6",
            "Fia": 10,
            "mains": 1,
            "Portée": "-",
            "Effet": "+2 en parade en 2e main",
            "Taille": "P",
            "AM": 0,
            "Poids": 1,
            "Prix": 465,
            "Race": "Humain",
            "Page": 14,
            "Source": "S&F"
        },
        {
            "Nom": "Attrape-lame",
            "Catégorie": "Lame courte",
            "Type": "T/P",
            "pré": 0,
            "Dispo": "C",
            "Dégats": "2D6",
            "Fia": 10,
            "mains": 1,
            "Portée": "-",
            "Effet": "Attrape-lame",
            "Taille": "P",
            "AM": 0,
            "Poids": 1,
            "Prix": 500,
            "Race": "Humain",
            "Page": 8,
            "Source": "Rodolf"
        },
        {
            "Nom": "Dague à rouelle halfeline",
            "Catégorie": "Lame courte",
            "Type": "T/P",
            "pré": 2,
            "Dispo": "R",
            "Dégats": "2D6+2",
            "Fia": 10,
            "mains": 1,
            "Portée": "-",
            "Effet": "Perforation",
            "Taille": "P",
            "AM": 1,
            "Poids": 1,
            "Prix": 485,
            "Race": "Non Humain",
            "Page": 83,
            "Source": "Base"
        },
        {
            "Nom": "Couperet nain",
            "Catégorie": "Lame courte",
            "Type": "T/C",
            "pré": 2,
            "Dispo": "R",
            "Dégats": "3D6",
            "Fia": 15,
            "mains": 1,
            "Portée": "-",
            "Effet": "-",
            "Taille": "P",
            "AM": 1,
            "Poids": 1.5,
            "Prix": 500,
            "Race": "Non Humain",
            "Page": 83,
            "Source": "Base"
        },
        {
            "Nom": "Croc de parade de l'école de la Vipère",
            "Catégorie": "Lame courte",
            "Type": "T/P",
            "pré": 1,
            "Dispo": "R",
            "Dégats": "2D6+2",
            "Fia": 10,
            "mains": 1,
            "Portée": "-",
            "Effet": "Parade sans malus",
            "Taille": "P",
            "AM": 1,
            "Poids": 1,
            "Prix": 0,
            "Race": "Sorceleur",
            "Page": 7,
            "Source": "DLC"
        },
        {
            "Nom": "Croc d'argent de l'école de la Vipère",
            "Catégorie": "Lame courte",
            "Type": "T/P",
            "pré": 2,
            "Dispo": "R",
            "Dégats": "1D6+2",
            "Fia": 10,
            "mains": 1,
            "Portée": "-",
            "Effet": "Poison (30%), Argent (3D6)",
            "Taille": "P",
            "AM": 1,
            "Poids": 1,
            "Prix": 0,
            "Race": "Sorceleur",
            "Page": 4,
            "Source": "DLC"
        },
        {
            "Nom": "Croc d'acier de l'école de la Vipère",
            "Catégorie": "Lame courte",
            "Type": "T/P",
            "pré": 2,
            "Dispo": "R",
            "Dégats": "4D6+2",
            "Fia": 15,
            "mains": 1,
            "Portée": "-",
            "Effet": "Perforation, Poison (30%), Météorite",
            "Taille": "P",
            "AM": 1,
            "Poids": 2,
            "Prix": 0,
            "Race": "Sorceleur",
            "Page": 4,
            "Source": "DLC"
        },
        {
            "Nom": "Epée de fer",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 0,
            "Dispo": "C",
            "Dégats": "2D6+2",
            "Fia": 10,
            "mains": 1,
            "Portée": "-",
            "Effet": "G",
            "Taille": 0,
            "AM": 1,
            "Poids": 150,
            "Prix": "Humain",
            "Page": 0,
            "Source": "Fan made"
        },
        {
            "Nom": "Epée de chevalier",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 0,
            "Dispo": "C",
            "Dégats": "2D6+4",
            "Fia": 15,
            "mains": 1,
            "Portée": "-",
            "Effet": "G",
            "Taille": 0,
            "AM": 2,
            "Poids": 270,
            "Prix": "Humain",
            "Page": 73,
            "Source": "Base"
        },
        {
            "Nom": "Gleddyf",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 2,
            "Dispo": "C",
            "Dégats": "3D6+2",
            "Fia": 10,
            "mains": 1,
            "Portée": "-",
            "Effet": "G",
            "Taille": 0,
            "AM": 3,
            "Poids": 285,
            "Prix": "Humain",
            "Page": 73,
            "Source": "Base"
        },
        {
            "Nom": "Fauchon de chasseur",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 0,
            "Dispo": "C",
            "Dégats": "3D6",
            "Fia": 15,
            "mains": 1,
            "Portée": "-",
            "Effet": "G",
            "Taille": 1,
            "AM": 1.5,
            "Poids": 325,
            "Prix": "Humain",
            "Page": 73,
            "Source": "Base"
        },
        {
            "Nom": "Barème",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 0,
            "Dispo": "C",
            "Dégats": "4D6",
            "Fia": 15,
            "mains": 1,
            "Portée": "-",
            "Effet": "G",
            "Taille": 1,
            "AM": 1.5,
            "Poids": 450,
            "Prix": "Humain",
            "Page": 0,
            "Source": "Fan made"
        },
        {
            "Nom": "Krigsverd",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 2,
            "Dispo": "C",
            "Dégats": "4D6+4",
            "Fia": 10,
            "mains": 1,
            "Portée": "-",
            "Effet": "G",
            "Taille": 0,
            "AM": 2,
            "Poids": 570,
            "Prix": "Humain",
            "Page": 73,
            "Source": "Base"
        },
        {
            "Nom": "Esboda",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 1,
            "Dispo": "P",
            "Dégats": "5D6",
            "Fia": 10,
            "mains": 1,
            "Portée": "-",
            "Effet": "-",
            "Taille": 1,
            "AM": 1.5,
            "Poids": 650,
            "Prix": "Humain",
            "Page": 73,
            "Source": "Base"
        },
        {
            "Nom": "Kord",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 0,
            "Dispo": "R",
            "Dégats": "5D6",
            "Fia": 15,
            "mains": 1,
            "Portée": "-",
            "Effet": "Saignement (25%)",
            "Taille": 1,
            "AM": 1,
            "Poids": 725,
            "Prix": "Humain",
            "Page": 73,
            "Source": "Base"
        },
        {
            "Nom": "Epée Ducal de Toussaint",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 0,
            "Dispo": "R",
            "Dégats": "5D6",
            "Fia": 10,
            "mains": 1,
            "Portée": "-",
            "Effet": "Perforation",
            "Taille": 0,
            "AM": 1,
            "Poids": 800,
            "Prix": "Humain",
            "Page": 165,
            "Source": "BoT"
        },
        {
            "Nom": "Messer elfe",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 2,
            "Dispo": "R",
            "Dégats": "3D6+4",
            "Fia": 15,
            "mains": 1,
            "Portée": "-",
            "Effet": "G",
            "Taille": 2,
            "AM": 2,
            "Poids": 595,
            "Prix": "Non Humain",
            "Page": 83,
            "Source": "Base"
        },
        {
            "Nom": "Sabre de cavalerie vrihedd",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 3,
            "Dispo": "R",
            "Dégats": "4D6+4",
            "Fia": 15,
            "mains": 1,
            "Portée": "-",
            "Effet": "Saignement (25%)",
            "Taille": 2,
            "AM": 2,
            "Poids": 595,
            "Prix": "Non Humain",
            "Page": 83,
            "Source": "Base"
        },
        {
            "Nom": "Deitmenae",
            "Catégorie": "Epées",
            "Type": "T",
            "pré": 2,
            "Dispo": "R",
            "Dégats": "4D6",
            "Fia": 15,
            "mains": 1,
            "Portée": "-",
            "Effet": "2D6 de dégats en plus la nuit. Saignement (50%), Perforation",
            "Taille": 1,
            "AM": 1.5,
            "Poids": 900,
            "Prix": "Non Humain",
            "Page": "",
            "Source": "Fan made"
        },
        {
            "Nom": "Epée d'acier de l'école de la Manticore",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 1,
            "Dispo": "R",
            "Dégats": "5D6+2",
            "Fia": 15,
            "mains": 1,
            "Portée": "-",
            "Effet": "Météorite, Perforation, Equilibré",
            "Taille": "-",
            "AM": 2,
            "Poids": 2.5,
            "Prix": 0,
            "Race": "Sorceleur",
            "Page": 4,
            "Source": "DLC"
        },
        {
            "Nom": "Epée en bois",
            "Catégorie": "Epées",
            "Type": "C",
            "pré": 0,
            "Dispo": "P",
            "Dégats": "2D6",
            "Fia": 10,
            "mains": 2,
            "Portée": "-",
            "Effet": "Non létal",
            "Taille": "G",
            "AM": 0,
            "Poids": 1,
            "Prix": 25,
            "Race": "Humain",
            "Page": "-",
            "Source": "Fan made"
        },
        {
            "Nom": "Épée longue de fer",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 0,
            "Dispo": "P",
            "Dégats": "2D6+2",
            "Fia": 15,
            "mains": 2,
            "Portée": "-",
            "Effet": "-",
            "Taille": "G",
            "AM": 0,
            "Poids": 1.5,
            "Prix": 160,
            "Race": "Humain",
            "Page": 73,
            "Source": "Base"
        },
        {
            "Nom": "Épée de chasseur de sorcières",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 0,
            "Dispo": "I",
            "Dégats": "4D6",
            "Fia": 15,
            "mains": 2,
            "Portée": "-",
            "Effet": "Saignement (25%), 1D6 vs non humain",
            "Taille": "-",
            "AM": 1,
            "Poids": 1.5,
            "Prix": 360,
            "Race": "Humain",
            "Page": "-",
            "Source": "Fan made"
        },
        {
            "Nom": "Lame vicovarienne",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 0,
            "Dispo": "R",
            "Dégats": "5D6+4",
            "Fia": 15,
            "mains": 2,
            "Portée": "-",
            "Effet": "Equilibré",
            "Taille": "-",
            "AM": 1,
            "Poids": 1.5,
            "Prix": 995,
            "Race": "Humain",
            "Page": 73,
            "Source": "Base"
        },
        {
            "Nom": "Epée de Viroledan",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 1,
            "Dispo": "R",
            "Dégats": "4D6+4",
            "Fia": 10,
            "mains": 2,
            "Portée": "-",
            "Effet": "Equilibrée, Saignement(30%), Poison(30%)",
            "Taille": "-",
            "AM": 1,
            "Poids": 2,
            "Prix": 995,
            "Race": "Humain",
            "Page": 165,
            "Source": "BoT"
        },
        {
            "Nom": "Flamberge de Toussaint",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": -1,
            "Dispo": "I",
            "Dégats": "6D6",
            "Fia": 15,
            "mains": 2,
            "Portée": "-",
            "Effet": "Allonge, Charge",
            "Taille": "-",
            "AM": 1,
            "Poids": 3.5,
            "Prix": 1025,
            "Race": "Humain",
            "Page": 165,
            "Source": "BoT"
        },
        {
            "Nom": "Torrwr",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 0,
            "Dispo": "R",
            "Dégats": "6D6",
            "Fia": 15,
            "mains": 2,
            "Portée": "-",
            "Effet": "Météorite, Perforation",
            "Taille": "-",
            "AM": 2,
            "Poids": 2,
            "Prix": 1075,
            "Race": "Humain",
            "Page": 73,
            "Source": "Base"
        },
        {
            "Nom": "Épée en météorite",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 1,
            "Dispo": "R",
            "Dégats": "5D6",
            "Fia": 20,
            "mains": 2,
            "Portée": "-",
            "Effet": "Équilibrée, Météorite",
            "Taille": "-",
            "AM": 2,
            "Poids": 3,
            "Prix": 875,
            "Race": "Non Humain",
            "Page": 83,
            "Source": "Base"
        },
        {
            "Nom": "Sihill de Mahakam",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 2,
            "Dispo": "R",
            "Dégats": "5D6+2",
            "Fia": 15,
            "mains": 2,
            "Portée": "-",
            "Effet": "Étourdissement (25%)",
            "Taille": "-",
            "AM": 2,
            "Poids": 2,
            "Prix": 950,
            "Race": "Non Humain",
            "Page": 0,
            "Source": "Fan made"
        },
        {
            "Nom": "Gwyhyr gnome",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 3,
            "Dispo": "R",
            "Dégats": "5D6+3",
            "Fia": 15,
            "mains": 2,
            "Portée": "-",
            "Effet": "Saignement (50%)",
            "Taille": "-",
            "AM": 2,
            "Poids": 2.5,
            "Prix": 1090,
            "Race": "Non Humain",
            "Page": 83,
            "Source": "Base"
        },
        {
            "Nom": "Lame de Tir Tochair",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 3,
            "Dispo": "R",
            "Dégats": "6D6",
            "Fia": 15,
            "mains": 2,
            "Portée": "-",
            "Effet": "Saignement (25%)",
            "Taille": "-",
            "AM": 2,
            "Poids": 3,
            "Prix": 1175,
            "Race": "Non Humain",
            "Page": 83,
            "Source": "Base"
        },
        {
            "Nom": "Epee de Dol Blathanna",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 1,
            "Dispo": "R",
            "Dégats": "6d6+3",
            "Fia": 15,
            "mains": 2,
            "Portée": "-",
            "Effet": "Equilibré, Météorite",
            "Taille": "-",
            "AM": 2,
            "Poids": 1.2,
            "Prix": 1250,
            "Race": "Non Humain",
            "Page": "-",
            "Source": "Fan made"
        },
        {
            "Nom": "Epée d'acier de witcher",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 0,
            "Dispo": "R",
            "Dégats": "4D6+2",
            "Fia": 15,
            "mains": 2,
            "Portée": "-",
            "Effet": "Météorite, Perforation",
            "Taille": "-",
            "AM": 2,
            "Poids": 2,
            "Prix": 0,
            "Race": "Sorceleur",
            "Page": 247,
            "Source": "Base"
        },
        {
            "Nom": "Epée d'argent de witcher",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 0,
            "Dispo": "R",
            "Dégats": "1D6+2",
            "Fia": 10,
            "mains": 2,
            "Portée": "-",
            "Effet": "Argent (3D6)",
            "Taille": "-",
            "AM": 2,
            "Poids": 1,
            "Prix": 0,
            "Race": "Sorceleur",
            "Page": 247,
            "Source": "Base"
        },
        {
            "Nom": "Epée d'acier de l'école du Loup",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 2,
            "Dispo": "R",
            "Dégats": "5D6+2",
            "Fia": 15,
            "mains": 2,
            "Portée": "-",
            "Effet": "Météorite, Perforation Amélioré",
            "Taille": "-",
            "AM": 2,
            "Poids": 2.5,
            "Prix": 0,
            "Race": "Sorceleur",
            "Page": "-",
            "Source": "DLC"
        },
        {
            "Nom": "Epée d'argent de l'école du Loup",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 2,
            "Dispo": "R",
            "Dégats": "2D6+2",
            "Fia": 10,
            "mains": 2,
            "Portée": "-",
            "Effet": "Argent (3D6), Perforation",
            "Taille": "-",
            "AM": 1,
            "Poids": 1.5,
            "Prix": 0,
            "Race": "Sorceleur",
            "Page": 5,
            "Source": "DLC"
        },
        {
            "Nom": "Epée d'acier de l'école du Griffon",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 1,
            "Dispo": "R",
            "Dégats": "5D6+2",
            "Fia": 15,
            "mains": 2,
            "Portée": "-",
            "Effet": "Météorite, Perforation, Focus(1)",
            "Taille": "-",
            "AM": 2,
            "Poids": 2.5,
            "Prix": 0,
            "Race": "Sorceleur",
            "Page": 3,
            "Source": "DLC"
        },
        {
            "Nom": "Epée d'argent de l'école du griffon",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 1,
            "Dispo": "R",
            "Dégats": "2D6+2",
            "Fia": 10,
            "mains": 2,
            "Portée": "-",
            "Effet": "Argent (3D6), Perforation, Focus(1)",
            "Taille": "-",
            "AM": 2,
            "Poids": 1.5,
            "Prix": 0,
            "Race": "Sorceleur",
            "Page": 3,
            "Source": "DLC"
        },
        {
            "Nom": "Epée d'argent de l'école du Chat",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 2,
            "Dispo": "R",
            "Dégats": "1D6+2",
            "Fia": 10,
            "mains": 2,
            "Portée": "-",
            "Effet": "Argent (3D6), Perforation, Saignement (30%)",
            "Taille": "-",
            "AM": 2,
            "Poids": 1.5,
            "Prix": 0,
            "Race": "Sorceleur",
            "Page": 3,
            "Source": "DLC"
        },
        {
            "Nom": "Epée d'acier de l'école du Chat",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 2,
            "Dispo": "R",
            "Dégats": "4D6+2",
            "Fia": 15,
            "mains": 2,
            "Portée": "-",
            "Effet": "Météorite, Perforation, Saignement (30%)",
            "Taille": "-",
            "AM": 2,
            "Poids": 2.5,
            "Prix": 0,
            "Race": "Sorceleur",
            "Page": 3,
            "Source": "DLC"
        },
        {
            "Nom": "Epée d'argent de l'école de l'Ours",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 0,
            "Dispo": "R",
            "Dégats": "3D6+2",
            "Fia": 10,
            "mains": 2,
            "Portée": "-",
            "Effet": "Argent (3D6), Ablation",
            "Taille": "-",
            "AM": 2,
            "Poids": 1.5,
            "Prix": 0,
            "Race": "Sorceleur",
            "Page": 3,
            "Source": "DLC"
        },
        {
            "Nom": "Epée d'acier de l'école de l'Ours",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 0,
            "Dispo": "R",
            "Dégats": "6D6+2",
            "Fia": 15,
            "mains": 2,
            "Portée": "-",
            "Effet": "Météorite, Perforation, Ablation",
            "Taille": "-",
            "AM": 2,
            "Poids": 2.5,
            "Prix": 0,
            "Race": "Sorceleur",
            "Page": 3,
            "Source": "DLC"
        },
        {
            "Nom": "Epée d'argent de l'école de la Manticore",
            "Catégorie": "Epées",
            "Type": "T/P",
            "pré": 2,
            "Dispo": "R",
            "Dégats": "1D6+2",
            "Fia": 10,
            "mains": 2,
            "Portée": "-",
            "Effet": "Argent (3D6), Equilibré",
            "Taille": "-",
            "AM": 2,
            "Poids": 1.5,
            "Prix": 0,
            "Race": "Sorceleur",
            "Page": 4,
            "Source": "Fan made"
        }
    ]
}